#!/bin/bash
 
for i in *.text
do  
	s2="${i%.text}"
	html="$s2.html"
	cp "$html" a

	../sundown.exe "$i" > b
	c=$(diff -Nup a b)
	if [ -z "$c" ] 
	then
		echo PASS "."
	else
		cat <<EOF > fixme	

--=-=-=-=-=-=-=-=-=-- 
FAIL $i 
EOF
		diff -Nup a b >> fixme
		vim -O "$html" fixme "$i"

	fi

done
